import type { Resource } from './types'

export const resources: Resource[] = [
  {
    id: 'r-001',
    name: 'payments-api-prod',
    type: 'EC2 Instance',
    provider: 'AWS',
    region: 'us-east-1',
    environment: 'production',
    criticality: 'critical',
    owner: 'payments',
    tags: ['pci', 'api'],
    openIssues: 4,
  },
  {
    id: 'r-002',
    name: 'transactions-ledger',
    type: 'Cloud SQL',
    provider: 'GCP',
    region: 'us-central1',
    environment: 'production',
    criticality: 'critical',
    owner: 'payments',
    tags: ['pci', 'database'],
    openIssues: 2,
  },
  {
    id: 'r-003',
    name: 'receipt-archive',
    type: 'S3 Bucket',
    provider: 'AWS',
    region: 'us-east-1',
    environment: 'production',
    criticality: 'high',
    owner: 'finance',
    tags: ['receipts', 'retention'],
    openIssues: 1,
  },
  {
    id: 'r-004',
    name: 'identity-gateway',
    type: 'App Service',
    provider: 'Azure',
    region: 'eastus',
    environment: 'production',
    criticality: 'critical',
    owner: 'identity',
    tags: ['auth', 'public'],
    openIssues: 3,
  },
  {
    id: 'r-005',
    name: 'checkout-worker-stg',
    type: 'Cloud Run',
    provider: 'GCP',
    region: 'us-central1',
    environment: 'staging',
    criticality: 'medium',
    owner: 'commerce',
    tags: ['checkout', 'worker'],
    openIssues: 0,
  },
  {
    id: 'r-006',
    name: 'catalog-cache',
    type: 'ElastiCache',
    provider: 'AWS',
    region: 'eu-west-1',
    environment: 'production',
    criticality: 'high',
    owner: 'catalog',
    tags: ['redis', 'catalog'],
    openIssues: 2,
  },
  {
    id: 'r-007',
    name: 'analytics-warehouse',
    type: 'BigQuery Dataset',
    provider: 'GCP',
    region: 'europe-west2',
    environment: 'production',
    criticality: 'medium',
    owner: 'data-platform',
    tags: ['analytics', 'pii'],
    openIssues: 5,
  },
  {
    id: 'r-008',
    name: 'ops-dashboard-dev',
    type: 'Static Web App',
    provider: 'Azure',
    region: 'westus2',
    environment: 'development',
    criticality: 'low',
    owner: 'platform',
    tags: ['internal', 'dashboard'],
    openIssues: 0,
  },
  {
    id: 'r-009',
    name: 'deployment-runner',
    type: 'IAM Role',
    provider: 'AWS',
    region: 'global',
    environment: 'development',
    criticality: 'high',
    owner: 'platform',
    tags: ['ci-cd', 'iam'],
    openIssues: 1,
  },
  {
    id: 'r-010',
    name: 'customer-profile-stg',
    type: 'Cosmos DB',
    provider: 'Azure',
    region: 'eastus2',
    environment: 'staging',
    criticality: 'medium',
    owner: 'customer-experience',
    tags: ['profiles', 'database'],
    openIssues: 3,
  },
  {
    id: 'r-011',
    name: 'fraud-detection-model',
    type: 'Vertex AI Endpoint',
    provider: 'GCP',
    region: 'us-east4',
    environment: 'production',
    criticality: 'high',
    owner: 'risk',
    tags: ['ml', 'fraud'],
    openIssues: 1,
  },
  {
    id: 'r-012',
    name: 'notifications-queue',
    type: 'Service Bus',
    provider: 'Azure',
    region: 'northeurope',
    environment: 'production',
    criticality: 'medium',
    owner: 'communications',
    tags: ['queue', 'notifications'],
    openIssues: 0,
  },
]
